    <div class="container">
        
       <?php  echo $this->form()->openTag($form); ?>
            <div class="form-group">
                <?php  echo $this->formLabel($form->get('u_name')); ?>
                <div class="col-sm-9">
                <?php  echo $this->formElement($form->get('u_name')); ?>
                </div>
                <?php  echo $this->formElementErrors($form->get('u_name')) ?>
            </div>
            <div class="form-group">
                <?php  echo $this->formLabel($form->get('upw')); ?>
                <div class="col-sm-9">
                    <?php  echo $this->formElement($form->get('upw')); ?>
                    <div><span id="status">&nbsp;</span></div>
                </div>
            </div>
            <div class="form-group" style="margin-top:0">
                <label class="col-sm-3"></label>
                <div class="col-sm-9">   
                    <?php  echo $this->formElement($form->get('submit')); ?>
                    <?php  echo $this->formElement($form->get('reset')); ?>
                </div>
            </div>
        <?php echo $this->form()->closeTag();?>
    </div>

<script type="text/javascript">
    $(document).ready(function()
    {
        $('.user').hide();
        $('.sidebar').hide();
        $('.topnav').hide();
        $("#upw").val('');
        //            $('.navbar').hide();
        $("#logincheck").submit(function() 
        { 
            var u_name = $("#u_name").val();
            var password = $("#upw").val();
            if(u_name.length ===0)
            {
                $("#status").html('<font color="#cc0000">Username Can not be blank</font>');
            }
            else if(password.length===0)
            {
                $("#status").html('<font color="#cc0000">Password can not be blank.</font>');
            }
            else
            {
                $("#status").html('&nbsp;Processing in.');
                 var data = {
                    u_name : u_name,
                    upw : password,
                    action : 'weblogin'
                }
                var url = "logincheck";
                $.post(url, data,function(respJson){
                    var resp =JSON.parse(respJson);
                    var responseCode = resp.statusCode;
                    var errMessage = resp.result;
                    if(responseCode == 200){
                         <?php if(isset($_SESSION['ref'])){?>
                             window.location.replace('<?php echo $_SESSION['ref'];?>');
                         <?php }else{ ?>
                            window.location.replace("tracker");
                         <?php } ?>
                    }
                    else if(resp.u_name){
                        $("#status").html('<font color="#cc0000">'+(resp.u_name.regexNotMatch)+'</font>');
                    }else if(resp.upw){
                        $("#status").html('<font color="#cc0000">'+(resp.upw.regexNotMatch)+'</font>');
                    }
                    else{
                        $("#status").html('<font color="#cc0000">Enter Correct Username & Password</font>');
                    }
                });
            }
            return false;
        });
    });
</script>

